function MPO_Mechanisms(sites,kw,L)
    # using the specific keyword (kw), program will build an MPO which is generated by autoMPO
    # Arguments: 
        # sites -> ITensor site indices
        # kw -> Method of connecting our units
        # L -> Number of units in our system
    # Returns:
        # H -> Stochastic Master Equation as an ITensor MPO

    ampo = AutoMPO(); #call the autoMPO function from ITensors

    if cmp(kw,"SingleUnit") == 0 #this creates the MPO representation of the master equation for a single L=1 CMOS unit


        ########################################
        #### b operators (bottom NOT gate) #####
        ########################################

        ### GAIN TERMS ###

        # Probability flows in from v0-ve
	    # P(v0 - ve,v1)(λu+(v0-ve;v1) + λd-(v0-ve;v1))
	    # λu+(v0-ve;v1):
	    ampo .+= "x+",1,"U+",2
	    # λd-(v0-ve;v1):
        ampo .+= "x+",1,"D-",1,"U-",2

	    # Probability flows in from v0+ve
        # P(v0+ve,v1)(λd+(v0+ve,v1) + λu-(v0+ve,v1))
        # λu-(v0+ve;v1):
        ampo .+= "x-",1,"U-",2
	    # λd+(v0+ve;v1):
        ampo .+= "x-",1,"D+",1,"U+",2

        ### LOSS (DIAGONAL) TERMS ###   

        # Probability flows out from v0
        # -P(v0,v1)(λu+(v0;v1) + λd-(v0;v1))
	    # λu+(v0;v1):
        ampo .-= "U+",2,"upperProj",1
	    # λd-(v0;v1):
        ampo .-= "D-",1,"U-",2,"upperProj",1       

        # Probability flows out from v0
        # -P(v0,v1)(λd+(v0;v1) + λu-(v0;v1))
	    # λu-(v0;v1):
        ampo .-= "U-",2,"lowerProj",1
        # λd+(v0;v1):
        ampo .-= "D+",1,"U+",2,"lowerProj",1

        #####################################
        #### t operators (Top NOT gate) #####
        #####################################

        ### GAIN TERMS ###

        # Probability flows in from v1-ve
        # P(v0,v1-ve)(λu+(v1-ve;v0) + λd-(v1-ve;v0))
	    # λu+(v1-ve;v0):
        ampo .+= "x+",2,"U+",1
	    # λd-(v1-ve;v0):
        ampo .+= "x+",2,"D-",2,"U-",1

        # Probability flows in from v1+ve
        # P(v0,v1+ve)(λd+(v1+ve;v0) + λu-(v1+ve;v0))
        #  λu-(v1+ve;v0):
        ampo .+= "x-",2,"U-",1
	    # λd+(v1+ve;v0):
        ampo .+= "x-",2,"D+",2,"U+",1

        ### LOSS (DIAGONAL) TERMS ###        	

        # Probability flows out from v1
	    # λu+(v1;v0):
        ampo .-= "U+",1,"upperProj",2
	    # λd-(v1;v0):
        ampo .-= "D-",2,"U-",1,"upperProj",2

        # Probability flows out from v1
        # -P(v0,v1)(λd+(v1;v0) + λu-(v1;v0))
	    # λu-(v1;v0):
        ampo .-= "U-",1,"lowerProj",2
        # λd+(v1;v0) : 
        ampo .-= "D+",2,"U+",1,"lowerProj",2

    end

    if cmp(kw,"Series") == 0 #this creates the MPO representation of the master equation for a chain of L CMOS units connected in series

	    for i=1:L #loop over the nodes i=0 -> i=L-1

            ########################################
            #### b operators (bottom NOT gate) #####
            ########################################

            ### GAIN TERMS ### (off diagonal)

            # Probability flows in from vi-1
            # P(vi - ve,v(i+1))(λu+(vi-ve;v(i+1)) + λd-(vi-ve;v(i+1)))
            # λu+(vi-ve;v(i+1)):
            ampo .+= "x+",i,"U+",(i+1)
            # λd-(vi-ve;v(i+1)):
            ampo .+= "x+",i,"D-",i,"U-",(i+1)

            # Probability flows in from vi+1
            # P(vi+ve,v(i+1))(λd+(vi+ve;v(i+1)) + λu-(vi+ve;v(i+1)))
            # λu-(vi+ve;v(i+1)):
            ampo .+= "x-",i,"U-",(i+1)
            # λd+(vi+ve;v(i+1)):
            ampo .+= "x-",i,"D+",i,"U+",(i+1)

            ### LOSS TERMS ### (diagonal)

            # Probability flows out from vi 
            # -P(vi,v(i+1))(λu+(vi;v(i+1)) + λd-(vi;v(i+1)))
            # λu+(vi;v(i+1)):
            ampo .-= "U+",(i+1),"upperProj",i
            # λd-(vi;v(i+1)):
            ampo .-= "D-",i,"U-",(i+1),"upperProj",i

            # Probability flows out from vi 
            # -P(vi,v(i+1))(λd+(vi;v(i+1)) + λu-(vi;v(i+1)))
            # λu-(vi;v(i+1)):
            ampo .-= "U-",(i+1),"lowerProj",i
            # λd+(vi;v(i+1)):
            ampo .-= "D+",i,"U+",(i+1),"lowerProj",i

            ########################################
            #### t operators (bottom NOT gate) #####
            ########################################

            ### GAIN TERMS ### (off diagonal)

            # Probability flows in from v(i+1)-1
            # P(vi,v(i+1)-ve)(λu+(v(i+1)-ve;vi) + λd-(v(i+1)-ve;vi))
            # λu+(v(i+1)-ve;vi):
            ampo .+= "x+",(i+1),"U+",i
            # λd-(v(i+1)-ve;vi):
            ampo .+= "x+",(i+1),"D-",(i+1),"U-",i

            # Probability flows in from v(i+1)+1 
            # P(vi,v(i+1)+ve)(λd+(v(i+1)+ve;vi) + λu-(v(i+1)+ve;vi))
            #  λu-(v(i+1)+ve;vi):
            ampo .+= "x-",(i+1),"U-",i
            # λd+(v(i+1)+ve;vi):
            ampo .+= "x-",(i+1),"D+",(i+1),"U+",i

            ### LOSS TERMS ### (diagonal)

            # Probability flows out from v(i+1) 
            # -P(vi,v(i+1))(λu+(v(i+1);vi) + λd-(v(i+1);vi))
            # λu+(v(i+1);vi):
            ampo .-= "U+",i,"upperProj",(i+1)
            # λd-(v(i+1);vi):
            ampo .-= "D-",(i+1),"U-",i,"upperProj",(i+1)

            # Probability flows out from v(i+1)
            # -P(vi,v(i+1))(λd+(v(i+1);vi) + λu-(v(i+1);vi))
            # λu-(v(i+1);vi):
            ampo .-= "U-",i,"lowerProj",(i+1)
            # λd+(v(i+1);vi) :
            ampo .-= "D+",(i+1),"U+",i,"lowerProj",(i+1)

	    end

    end    

    H = MPO(ampo,sites;cutoff=0)

end
