function Dissipation_MPO(sites,kw,L)
    # using the specific keyword (kw), program will build an MPO which is generated by autoMPO
    # Arguments: 
        # sites -> ITensor site indices
        # M -> Even Cap on Discrete Voltage Space
        # kw -> Method of connecting our units
        # vDD_vT, ve_vT, nval -> Parameters of our circuit
        # L -> Number of units in our system
    # Returns:
        # HDiss -> The MPO operator that computes the steady state dissipation

    ampo = AutoMPO(); #call the autoMPO function from ITensors

    if cmp(kw,"SingleUnit") == 0 #this creates the MPO representation of the master equation for a single L=1 CMOS unit

        ########################################
        #### b operators (bottom NOT gate) #####
        ########################################

        ##  NMOS
        # λu-(v0;v1):
        ampo .+= "dQ-",1,"U-",2
	    # λd-(v0-ve;v1):
        ampo .-= "dQ-",1,"x+",1,"D-",1,"U-",2

        ##  PMOS
        # λu+(v0;v1):
        ampo .+= "dQ+",1,"U+",2 
	    # λd+(v0+ve;v1):
        ampo .-= "dQ+",1,"x-",1,"D+",1,"U+",2

        #####################################
        #### t operators (Top NOT gate) #####
        #####################################

        #  NMOS
        # λu-(v1;v0):
        ampo .+= "dQ-",2,"U-",1
	    # λd-(v1-ve;v0):
        ampo .-= "dQ-",2,"x+",2,"D-",2,"U-",1

        #  PMOS
        # λu+(v1;v0):
        ampo .+= "dQ+",2,"U+",1
	    # λd+(v1+ve;v0):
        ampo .-= "dQ+",2,"x-",2,"D+",2,"U+",1

    end

    if cmp(kw,"Series") == 0 #this creates the MPO representation of the master equation for a chain of L CMOS units connected in series

	    for i=1:L #loop over the nodes i=0 -> i=L-1
		@show i
		@show i+1
            ########################################
            #### b operators (bottom NOT gate) #####
            ########################################

            #  NMOS
            # λu-(vi;v(i+1)):
            ampo .+= "dQ-",i,"U-",(i+1)
            # λd-(vi-ve;v(i+1)):
            ampo .-= "dQ-",i,"x+",i,"D-",i,"U-",(i+1)

            #  PMOS
            # λu+(vi;v(i+1)):
            ampo .+= "dQ+",i,"U+",(i+1)
            # λd+(vi+ve;v(i+1)):
            ampo .-= "dQ+",i,"x-",i,"D+",i,"U+",(i+1)

            ########################################
            #### t operators (bottom NOT gate) #####
            ########################################

            #  NMOS
            # λu-(v(i+1);vi):
            ampo .-= "dQ-",(i+1),"U-",i
            # λd-(v(i+1)-ve;vi):
            ampo .+= "dQ-",(i+1),"x+",(i+1),"D-",(i+1),"U-",i

            #  PMOS
            # λu+(v(i+1);vi):
            ampo .-= "dQ+",(i+1),"U+",i
            # λd+(v(i+1)+ve;vi):
            ampo .+= "dQ+",(i+1),"x-",(i+1),"D+",(i+1),"U+",i

	    end

    end    

    if cmp(kw,"SeriesOrder") == 0 #this creates the MPO representation of the master equation for a chain of L CMOS units connected in series

            for i=1:L #loop over the nodes i=0 -> i=L-1
            ########################################
            #### b operators (bottom NOT gate) #####
            ########################################

            #  NMOS
            # λu-(vi;v(i+1)):
            ampo .+= "U-",(i+1),"dQ-",i
            # λd-(vi-ve;v(i+1)):
            ampo .-= "x+",i,"D-",i,"U-",(i+1),"dQ-",i

            #  PMOS
            # λu+(vi;v(i+1)):
            ampo .+= "U+",(i+1),"dQ+",i
            # λd+(vi+ve;v(i+1)):
            ampo .-= "x-",i,"D+",i,"U+",(i+1),"dQ+",i

            ########################################
            #### t operators (bottom NOT gate) #####
            ########################################

            #  NMOS
            # λu-(v(i+1);vi):
            ampo .-= "U-",i,"dQ-",(i+1)
            # λd-(v(i+1)-ve;vi):
            ampo .+= "x+",(i+1),"D-",(i+1),"U-",i,"dQ-",(i+1)

            #  PMOS
            # λu+(v(i+1);vi):
            ampo .-= "U+",i,"dQ+",(i+1)
            # λd+(v(i+1)+ve;vi):
            ampo .+= "x-",(i+1),"D+",(i+1),"U+",i,"dQ+",(i+1)

            end

    end

    if cmp(kw,"SeriesCurrent") == 0 #this creates the MPO representation of the master equation for a chain of L CMOS units connected in series

            for i=1:L #loop over the nodes i=0 -> i=L-1
                @show i
                @show i+1
            ########################################
            #### b operators (bottom NOT gate) #####
            ########################################

            #  NMOS
            # λu-(vi;v(i+1)):
            ampo .+= i,"U-",(i+1)
            # λd-(vi-ve;v(i+1)):
            ampo .-= "x+",i,"D-",i,"U-",(i+1)

            #  PMOS
            # λu+(vi;v(i+1)):
            ampo .+= "U+",(i+1)
            # λd+(vi+ve;v(i+1)):
            ampo .-= "x-",i,"D+",i,"U+",(i+1)

            ########################################
            #### t operators (bottom NOT gate) #####
            ########################################

            #  NMOS
            # λu-(v(i+1);vi):
            ampo .-= "U-",i
            # λd-(v(i+1)-ve;vi):
            ampo .+= "x+",(i+1),"D-",(i+1),"U-",i

            #  PMOS
            # λu+(v(i+1);vi):
            ampo .-= "U+",i
            # λd+(v(i+1)+ve;vi):
            ampo .+= "x-",(i+1),"D+",(i+1),"U+",i

            end

    end

    Hdiss = MPO(ampo,sites;cutoff=0)

end
